### PR TITLE
Add missing MSDN links

### PR DESCRIPTION
**Pull request by diversenok**
This pull request adds more links, mostly to uncategorized portions of MS docs like developer notes.

### CODE REVIEW

**Comment by m417z** [comment]
Here's another one that I found:
`RtlPointerToOffset`
https://learn.microsoft.com/en-us/previous-versions/ff553171(v=vs.85)
Interestingly, it links to `RtlOffsetToPointer` which is not available.
Not sure if there are more such missing links, perhaps you can generalize it using your methods.

**Comment by m417z** [comment]
> With the previous versions, even their own search on the website doesn't help much

Well, it does find `RtlPointerToOffset`:
https://learn.microsoft.com/en-us/search/?terms=RtlPointerToOffset&dataSource=previousVersions
Looks like something that can be automated.

> Can you also add some visual indication for links to external resources?

I thought about that. And I guess it's better to have them open in a new tab, too.

**Comment by diversenok** [comment]
> Well, it does find RtlPointerToOffset

Oh, I see, you need to search specifically for previous versions; it doesn't find these pages from the main search of https://learn.microsoft.com

**Comment by m417z** [comment]
> > Can you also add some visual indication for links to external resources?
> 
> I thought about that. And I guess it's better to have them open in a new tab, too.

Done!

**Pull request merged**
